### ISSUE TITLE
Doesn't Support Collection Literals

### ISSUE THREAD

**Issue by SorenSaket** [TwentyFourMinutes/BidirectionalDict#2]
BiDirectionalDict doesn't support Collection Literals since theres no Add method.

To solve this either rename AddOrUpdate()  to Add()  or create a new Add() method.

To learn More:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions

**Comment by TwentyFourMinutes** [comment]
@SorenSaket You are correct, however `BiDirectionalDict` requires a `Key` and `Value`, like normal dictionaries. Collection Literals do, at the time of writing, not support Dictionaries. See https://github.com/dotnet/csharplang/issues/7822.

**Comment by SorenSaket** [comment]
Theres a difference between a collection literal and a dictionary literal. There's still advantages in implementing support for collection literals.

Implementation of Collection literals would allow for this:
```
BiDictionary<int, int> test = [
    new  (1,1)
    new  (21,3)
];
```

Support can be added by simply adding this to BiDictionary.cs:

```
public void Add((TFirst, TSecond) value)
{
  if (!_firstToSecond.ContainsKey(value.Item1))
  {
  _firstToSecond[value.Item1] = value.Item2;
  }
  
  if (!_secondToFirst.ContainsKey(value.Item2))
  {
  _secondToFirst[value.Item2] = value.Item1;
  }
}
```
The code works because the function is named add and takes a single tuple as input. You can alternativly implement as KeyValuePair instead of tuple.
